const fs = require("fs");
const path = require("path");

function main() {
  const artifactPath = path.join(
    __dirname,
    "../artifacts/contracts/DepositEscrow.sol/DepositEscrow.json"
  );

  if (!fs.existsSync(artifactPath)) {
    console.error("Artifact file not found! Did you run `npx hardhat compile`?");
    process.exit(1);
  }

  const rawData = fs.readFileSync(artifactPath);
  const artifact = JSON.parse(rawData);

  const abiString = JSON.stringify(artifact.abi, null, 2);

  const outputContent = `// Automatically generated by scripts/export-abi.js. Do not edit manually.

export const DepositEscrowABI = ${abiString} as const;

export const contractAddresses = {
  sepolia: "0x0000000000000000000000000000000000000000",
  mainnet: "0x0000000000000000000000000000000000000000"
} as const;
`;

  const outputPath = path.join(__dirname, "../index.ts");
  fs.writeFileSync(outputPath, outputContent);
  console.log(`Successfully generated index.ts with DepositEscrowABI at: ${outputPath}`);
}

main();
