// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title DepositEscrow
 * @notice AI-Oracle controlled milestone crowdfunding escrow built for Base.
 */
contract DepositEscrow is ReentrancyGuard, Ownable {
    
    struct Campaign {
        address payable creator;
        uint256 goal;
        uint256 deadline;
        uint256 totalFunded;
        uint256 currentMilestone;
        uint256[] milestoneTranches; // Array of percentages (e.g., [30, 30, 40]) summing to 100
        bool isFailed;
        bool isCompleted;
    }

    // Identity of the backend execution automation environment
    address public aiOracle;
    uint256 public campaignCount;

    // campaignId => Campaign details
    mapping(uint256 => Campaign) public campaigns;
    
    // campaignId => contributor => amount deposited
    mapping(uint256 => mapping(address => uint256)) public contributions;

    // Events
    event CampaignCreated(uint256 indexed campaignId, address indexed creator, uint256 goal, uint256 deadline);
    event Funded(uint256 indexed campaignId, address indexed contributor, uint256 amount);
    event MilestoneApproved(uint256 indexed campaignId, uint256 indexed milestoneIndex, uint256 amountReleased);
    event CampaignFailed(uint256 indexed campaignId, string reason);
    event RefundClaimed(uint256 indexed campaignId, address indexed contributor, uint256 amount);

    modifier onlyOracle() {
        require(msg.sender == aiOracle, "DepositEscrow: Caller is not the authorized AI Oracle");
        _;
    }

    constructor(address _aiOracle) Ownable(msg.sender) {
        require(_aiOracle != address(0), "DepositEscrow: Invalid Oracle address");
        aiOracle = _aiOracle;
    }

    /**
     * @notice Allows creators to launch a new campaigns with milestone targets.
     * @param _goal Dynamic funding target in wei.
     * @param _duration Time until campaign closes in seconds.
     * @param _tranches Allocation percentages per milestone. Must sum exactly to 100.
     */
    function createCampaign(
        uint256 _goal, 
        uint256 _duration, 
        uint256[] calldata _tranches
    ) external returns (uint256) {
        require(_goal > 0, "DepositEscrow: Goal must be greater than zero");
        require(_duration > 0, "DepositEscrow: Duration must be greater than zero");
        require(_tranches.length > 0, "DepositEscrow: Must include at least one tranche");
        
        uint256 totalPercentage = 0;
        for (uint256 i = 0; i < _tranches.length; i++) {
            totalPercentage += _tranches[i];
        }
        require(totalPercentage == 100, "DepositEscrow: Milestone percentages must equal 100");

        campaignCount++;
        
        campaigns[campaignCount] = Campaign({
            creator: payable(msg.sender),
            goal: _goal,
            deadline: block.timestamp + _duration,
            totalFunded: 0,
            currentMilestone: 0,
            milestoneTranches: _tranches,
            isFailed: false,
            isCompleted: false
        });

        emit CampaignCreated(campaignCount, msg.sender, _goal, block.timestamp + _duration);
        return campaignCount;
    }

    /**
     * @notice Allows public contributors to escrow funds into a campaign.
     */
    function fund(uint256 _campaignId) external payable nonReentrant {
        Campaign storage campaign = campaigns[_campaignId];
        require(block.timestamp < campaign.deadline, "DepositEscrow: Campaign funding window has passed");
        require(!campaign.isFailed, "DepositEscrow: Campaign has been flagged as failed");
        require(msg.value > 0, "DepositEscrow: Contribution must be greater than zero");

        campaign.totalFunded += msg.value;
        contributions[_campaignId][msg.sender] += msg.value;

        emit Funded(_campaignId, msg.sender, msg.value);
    }

    /**
     * @notice Invoked strictly by the backend microservice executing automated AI evaluations.
     * @param _campaignId Identity of the target campaign.
     * @param _isApproved Outcome generated by the automated validation layer.
     */
    function approveMilestone(uint256 _campaignId, bool _isApproved) external onlyOracle nonReentrant {
        Campaign storage campaign = campaigns[_campaignId];
        require(campaign.totalFunded >= campaign.goal, "DepositEscrow: Campaign did not reach its funding goal");
        require(!campaign.isFailed, "DepositEscrow: Campaign is marked as failed");
        require(!campaign.isCompleted, "DepositEscrow: Campaign already fully executed");

        if (_isApproved) {
            uint256 currentMilestoneIdx = campaign.currentMilestone;
            uint256 percentage = campaign.milestoneTranches[currentMilestoneIdx];
            
            // Calculate payout amount relative to total campaign funding pool
            uint256 payoutAmount = (campaign.totalFunded * percentage) / 100;
            
            campaign.currentMilestone++;
            if (campaign.currentMilestone == campaign.milestoneTranches.length) {
                campaign.isCompleted = true;
            }

            (bool success, ) = campaign.creator.call{value: payoutAmount}("");
            require(success, "DepositEscrow: Payout transfer failed");

            emit MilestoneApproved(_campaignId, currentMilestoneIdx, payoutAmount);
        } else {
            // AI Oracle marked evidence as critical failure or unresolvable fraud
            campaign.isFailed = true;
            emit CampaignFailed(_campaignId, "AI Oracle rejected milestone evidence execution");
        }
    }

    /**
     * @notice Allows safety fallback refunds if a campaign misses goals or fails an AI milestone audit.
     */
    function claimRefund(uint256 _campaignId) external nonReentrant {
        Campaign storage campaign = campaigns[_campaignId];
        
        bool missedGoal = (block.timestamp >= campaign.deadline && campaign.totalFunded < campaign.goal);
        bool failedAudit = campaign.isFailed;
        
        require(missedGoal || failedAudit, "DepositEscrow: Campaign not eligible for refunds");

        uint256 contributedAmount = contributions[_campaignId][msg.sender];
        require(contributedAmount > 0, "DepositEscrow: No outstanding contributions found");

        // Prevent double claiming
        contributions[_campaignId][msg.sender] = 0;

        (bool success, ) = payable(msg.sender).call{value: contributedAmount}("");
        require(success, "DepositEscrow: Refund payout failed");

        emit RefundClaimed(_campaignId, msg.sender, contributedAmount);
    }

    /**
     * @notice Fallback ownership adjustments for Oracle credential rotation.
     */
    function updateOracle(address _newOracle) external onlyOwner {
        require(_newOracle != address(0), "DepositEscrow: Invalid address");
        aiOracle = _newOracle;
    }
}
